export const GET_COURSE_CATEGORIES = 'GET_COURSE_CATEGORIES';
export const GET_COURSE_CATEGORIES_FAIL = 'GET_COURSE_CATEGORIES_FAIL';

export const COURSE_CATEGORIES_LOADING = 'COURSE_CATEGORIES_LOADING';

export const CREATE_COURSE_CATEGORY = 'CREATE_COURSE_CATEGORY';
export const CREATE_COURSE_CATEGORY_FAIL = 'CREATE_COURSE_CATEGORY_FAIL';

export const DELETE_COURSE_CATEGORY = 'DELETE_COURSE_CATEGORY';
export const DELETE_COURSE_CATEGORY_FAIL = 'DELETE_COURSE_CATEGORY_FAIL';

export const UPDATE_COURSE_CATEGORY = 'UPDATE_COURSE_CATEGORY';
export const UPDATE_COURSE_CATEGORY_FAIL = 'UPDATE_COURSE_CATEGORY_FAIL';