export const GET_CHALLENGE_QUIZES = 'GET_CHALLENGE_QUIZES'
export const CHALLENGE_QUIZES_LOADING = 'CHALLENGE_QUIZES_LOADING'

export const GET_ONE_CHALLENGE_QUIZ = 'GET_ONE_CHALLENGE_QUIZ'
export const GET_ONE_CHALLENGE_QUIZ_FAIL = 'GET_ONE_CHALLENGE_QUIZ_FAIL'

export const GET_CATEGORY_CHALLENGE_QUIZES = 'GET_CATEGORY_CHALLENGE_QUIZES'
export const GET_CATEGORY_CHALLENGE_QUIZES_FAIL = 'GET_CATEGORY_CHALLENGE_QUIZES_FAIL'

export const GET_NOTES_CHALLENGE_QUIZES = 'GET_NOTES_CHALLENGE_QUIZES'
export const GET_NOTES_CHALLENGE_QUIZES_FAIL = 'GET_NOTES_CHALLENGE_QUIZES_FAIL'

export const CREATE_CHALLENGE_QUIZ = 'CREATE_CHALLENGE_QUIZ'
export const CREATE_CHALLENGE_QUIZ_FAIL = 'CREATE_CHALLENGE_QUIZ_FAIL'

export const UPDATE_CHALLENGE_QUIZ = 'UPDATE_CHALLENGE_QUIZ'
export const UPDATE_CHALLENGE_QUIZ_FAIL = 'UPDATE_CHALLENGE_QUIZ_FAIL'

export const DELETE_CHALLENGE_QUIZ = 'DELETE_CHALLENGE_QUIZ'
export const DELETE_CHALLENGE_QUIZ_FAIL = 'DELETE_CHALLENGE_QUIZ_FAIL'

export const GET_ALL_CHALLENGE_QUIZES = 'GET_ALL_CHALLENGE_QUIZES'
export const ALL_CHALLENGE_QUIZES_LOADING = 'ALL_CHALLENGE_QUIZES_LOADING'
