export const CHALLENGE_QUESTIONS_LOADING = 'CHALLENGE_QUESTIONS_LOADING';
export const GET_CHALLENGE_QUESTIONS = 'GET_CHALLENGE_QUESTIONS';

export const GET_ONE_CHALLENGE_QUESTION = 'GET_ONE_CHALLENGE_QUESTION';
export const GET_ONE_CHALLENGE_QUESTION_FAIL = 'GET_ONE_CHALLENGE_QUESTION_FAIL';

export const ADD_CHALLENGE_QUESTION = 'ADD_CHALLENGE_QUESTION';
export const ADD_CHALLENGE_QUESTION_FAIL = 'ADD_CHALLENGE_QUESTION_FAIL';

export const UPDATE_CHALLENGE_QUESTION = 'UPDATE_CHALLENGE_QUESTION';
export const UPDATE_CHALLENGE_QUESTION_FAIL = 'UPDATE_CHALLENGE_QUESTION_FAIL';

export const DELETE_CHALLENGE_QUESTION = 'DELETE_CHALLENGE_QUESTION';
export const DELETE_CHALLENGE_QUESTION_FAIL = 'DELETE_CHALLENGE_QUESTION_FAIL';

