export const GET_BLOG_POSTS_VIEWS = 'GET_BLOG_POSTS_VIEWS';
export const GET_BLOG_POSTS_VIEWS_FAIL = 'GET_BLOG_POSTS_VIEWS_FAIL';

export const GET_RECENT_TEN_VIEWS = 'GET_RECENT_TEN_VIEWS';
export const GET_RECENT_TEN_VIEWS_FAIL = 'GET_RECENT_TEN_VIEWS_FAIL';

export const GET_ONE_BLOG_POST_VIEW = 'GET_ONE_BLOG_POST_VIEW';
export const GET_ONE_BLOG_POST_VIEW_FAIL = 'GET_ONE_BLOG_POST_VIEW_FAIL';

export const GET_BLOG_POSTS_VIEWS_BY_CATEGORY = 'GET_BLOG_POSTS_VIEWS_BY_CATEGORY';
export const GET_BLOG_POSTS_VIEWS_BY_CATEGORY_FAIL = 'GET_BLOG_POSTS_VIEWS_BY_CATEGORY_FAIL';

export const BLOG_POSTS_VIEWS_LOADING = 'BLOG_POSTS_VIEWS_LOADING';

export const CREATE_BLOG_POST_VIEW = 'CREATE_BLOG_POST_VIEW';
export const CREATE_BLOG_POST_VIEW_FAIL = 'CREATE_BLOG_POST_VIEW_FAIL';

export const DELETE_BLOG_POST_VIEW = 'DELETE_BLOG_POST_VIEW';
export const DELETE_BLOG_POST_VIEW_FAIL = 'DELETE_BLOG_POST_VIEW_FAIL';

export const UPDATE_BLOG_POST_VIEW = 'UPDATE_BLOG_POST_VIEW';
export const UPDATE_BLOG_POST_VIEW_FAIL = 'UPDATE_BLOG_POST_VIEW_FAIL';