export const GET_SCHOOLS = 'GET_SCHOOLS';
export const GET_SCHOOLS_FAIL = 'GET_SCHOOLS_FAIL';

export const GET_ONE_SCHOOL = 'GET_ONE_SCHOOL';
export const GET_ONE_SCHOOL_FAIL = 'GET_ONE_SCHOOL_FAIL';

export const SCHOOLS_LOADING = 'SCHOOLS_LOADING';

export const CREATE_SCHOOL = 'CREATE_SCHOOL';
export const CREATE_SCHOOL_FAIL = 'CREATE_SCHOOL_FAIL';

export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const DELETE_SCHOOL_FAIL = 'DELETE_SCHOOL_FAIL';

export const UPDATE_SCHOOL = 'UPDATE_SCHOOL';
export const UPDATE_SCHOOL_FAIL = 'UPDATE_SCHOOL_FAIL';