export const GET_NOTES = 'GET_NOTES'
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL'

export const GET_NOTES_BY_CHAPTER = 'GET_NOTES_BY_CHAPTER'
export const GET_NOTES_BY_CHAPTER_FAIL = 'GET_NOTES_BY_CHAPTER_FAIL'

export const NOTES_LOADING = 'NOTES_LOADING'
export const NOTES_BY_CHAPTER_LOADING = 'NOTES_BY_CHAPTER_LOADING'

export const CREATE_NOTE = 'CREATE_NOTE'
export const CREATE_NOTE_FAIL = 'CREATE_NOTE_FAIL'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'

export const REMOVE_QUIZ_NOTES = 'REMOVE_QUIZ_NOTES'
export const REMOVE_QUIZ_NOTES_FAIL = 'REMOVE_QUIZ_NOTES_FAIL'

export const DELETE_NOTE = 'DELETE_NOTE'
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL'

export const UPDATE_NOTE = 'UPDATE_NOTE'
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL'

export const ADD_NOTES_QUIZZES = 'ADD_NOTES_QUIZZES'
export const ADD_NOTES_QUIZZES_FAIL = 'ADD_NOTES_QUIZZES_FAIL'

export const GET_LANDING_DISPLAY_NOTES = 'GET_LANDING_DISPLAY_NOTES'
export const GET_LANDING_DISPLAY_NOTES_FAIL = 'GET_LANDING_DISPLAY_NOTES_FAIL'
export const LANDING_DISPLAY_NOTES_LOADING = 'LANDING_DISPLAY_NOTES_LOADING'

export const GET_ONE_NOTE_PAPER = 'GET_ONE_NOTE_PAPER'
export const GET_ONE_NOTE_PAPER_FAIL = 'GET_ONE_NOTE_PAPER_FAIL'
export const GET_ONE_NOTE_PAPER_LOADING = 'GET_ONE_NOTE_PAPER_LOADING'

export const GET_LANDING_DISPLAY_NO_LIMIT_NOTES = 'GET_LANDING_DISPLAY_NO_LIMIT_NOTES'
export const LANDING_DISPLAY_NOTES_NO_LIMIT_LOADING = 'LANDING_DISPLAY_NOTES_NO_LIMIT_LOADING'
export const GET_LANDING_DISPLAY_NO_LIMIT_NOTES_FAIL = 'GET_LANDING_DISPLAY_NO_LIMIT_NOTES_FAIL'

export const GET_NOTES_BY_COURSE_CATEGORY = 'GET_NOTES_BY_COURSE_CATEGORY'
export const GET_NOTES_BY_COURSE_CATEGORY_FAIL = 'GET_NOTES_BY_COURSE_CATEGORY_FAIL'
export const NOTES_BY_COURSE_CATEGORY_LOADING = 'NOTES_BY_COURSE_CATEGORY_LOADING'
