export const GET_CONTACTS = 'GET_CONTACTS'
export const CONTACTS_LOADING = 'CONTACTS_LOADING'

export const GET_USER_CONTACTS = 'GET_USER_CONTACTS'
export const GET_USER_CONTACTS_FAIL = 'GET_USER_CONTACTS_FAIL'

export const GET_CONTACT = 'GET_CONTACT'
export const ADD_CONTACT = 'ADD_CONTACT'
export const REPLY_CONTACT = 'REPLY_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL'
export const REPLY_CONTACT_FAIL = 'REPLY_CONTACT_FAIL'
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL'