export const GET_CONTACTS = 'GET_CONTACTS'
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL'
export const CONTACTS_LOADING = 'CONTACTS_LOADING'

export const GET_ONE_CONTACT = 'GET_ONE_CONTACT'
export const ONE_CONTACT_LOADING = 'ONE_CONTACT_LOADING'
export const GET_ONE_CONTACT_FAIL = 'GET_ONE_CONTACT_FAIL'

export const ADD_ROOMS_MESSAGE = 'ADD_ROOMS_MESSAGE'
export const ADD_ROOMS_MESSAGE_FAIL = 'ADD_ROOMS_MESSAGE_FAIL'

export const GET_CREATE_CHAT_ROOM = 'GET_CREATE_CHAT_ROOM'
export const GET_CREATE_CHAT_ROOM_FAIL = 'GET_CREATE_CHAT_ROOM_FAIL'

export const GET_ROOM_MESSAGES = 'GET_ROOM_MESSAGES'
export const GET_ROOM_MESSAGES_FAIL = 'GET_ROOM_MESSAGES_FAIL'
export const ROOM_LOADING = 'ROOM_LOADING'

export const GET_USER_CONTACTS = 'GET_USER_CONTACTS'
export const GET_USER_CONTACTS_FAIL = 'GET_USER_CONTACTS_FAIL'

export const GET_CONTACT = 'GET_CONTACT'
export const ADD_CONTACT = 'ADD_CONTACT'
export const REPLY_CONTACT = 'REPLY_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL'
export const REPLY_CONTACT_FAIL = 'REPLY_CONTACT_FAIL'
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL'