export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL'

export const GET_ONE_COMMENT = 'GET_ONE_COMMENT'
export const GET_ONE_COMMENT_FAIL = 'GET_ONE_COMMENT_FAIL'

export const GET_QUESTION_COMMENTS = 'GET_QUESTION_COMMENTS'
export const GET_QUESTION_COMMENTS_FAIL = 'GET_QUESTION_COMMENTS_FAIL'

export const GET_COMMENTS_BY_QUIZ = 'GET_COMMENTS_BY_QUIZ'
export const GET_COMMENTS_BY_QUIZ_FAIL = 'GET_COMMENTS_BY_QUIZ_FAIL'
export const COMMENTS_BY_QUIZ_LOADING = 'COMMENTS_BY_QUIZ_LOADING'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL'

export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL'

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'

export const COMMENTS_LOADING = 'COMMENTS_LOADING'

export const GET_PAGINATED_COMMENTS = 'GET_PAGINATED_COMMENTS'
export const GET_PAGINATED_COMMENTS_FAIL = 'GET_PAGINATED_COMMENTS_FAIL'
export const PAGINATED_COMMENTS_LOADING = 'PAGINATED_COMMENTS_LOADING'

export const GET_PENDING_COMMENTS = 'GET_PENDING_COMMENTS'
export const GET_PENDING_COMMENTS_FAIL = 'GET_PENDING_COMMENTS_FAIL'
export const PENDING_COMMENTS_LOADING = 'PENDING_COMMENTS_LOADING'

export const APPROVE_COMMENT = 'APPROVE_COMMENT'
export const APPROVE_COMMENT_FAIL = 'APPROVE_COMMENT_FAIL'
export const REJECT_COMMENT = 'REJECT_COMMENT'
export const REJECT_COMMENT_FAIL = 'REJECT_COMMENT_FAIL'