export const GET_SCORES = 'GET_SCORES';
export const SCORES_LOADING = 'SCORES_LOADING';

export const GET_RANKING_SCORES = 'GET_RANKING_SCORES';
export const GET_RANKING_SCORES_FAIL = 'GET_RANKING_SCORES_FAIL';

export const GET_TAKER_SCORES = 'GET_TAKER_SCORES';
export const GET_TAKER_SCORES_FAIL = 'GET_TAKER_SCORES_FAIL';

export const GET_CREATOR_SCORES = 'GET_CREATOR_SCORES';
export const GET_CREATOR_SCORES_FAIL = 'GET_CREATOR_SCORES_FAIL';

export const GET_POPULAR_QUIZES = 'GET_POPULAR_QUIZES';
export const GET_POPULAR_QUIZES_FAIL = 'GET_POPULAR_QUIZES_FAIL';

export const GET_MONTHLY_USER = 'GET_MONTHLY_USER';
export const GET_MONTHLY_USER_FAIL = 'GET_MONTHLY_USER_FAIL';

export const GET_ONE_SCORE = 'GET_ONE_SCORE';
export const GET_ONE_SCORE_FAIL = 'GET_ONE_SCORE_FAIL';

export const CREATE_SCORE = 'CREATE_SCORE';
export const CREATE_SCORE_FAIL = 'CREATE_SCORE_FAIL';

export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_SCORE_FAIL = 'UPDATE_SCORE_FAIL';

export const DELETE_SCORE = 'DELETE_SCORE';
export const DELETE_SCORE_FAIL = 'DELETE_SCORE_FAIL';
