export const GET_BLOG_POSTS = 'GET_BLOG_POSTS';
export const GET_BLOG_POSTS_FAIL = 'GET_BLOG_POSTS_FAIL';

export const GET_ONE_BLOG_POST = 'GET_BLOG_POST';
export const GET_ONE_BLOG_POST_FAIL = 'GET_ONE_BLOG_POST_FAIL';

export const GET_BLOG_POSTS_BY_CATEGORY = 'GET_BLOG_POSTS_BY_CATEGORY';
export const GET_BLOG_POSTS_BY_CATEGORY_FAIL = 'GET_BLOG_POSTS_BY_CATEGORY_FAIL';

export const BLOG_POSTS_LOADING = 'BLOG_POSTS_LOADING';

export const CREATE_BLOG_POST = 'CREATE_BLOG_POST';
export const CREATE_BLOG_POST_FAIL = 'CREATE_BLOG_POST_FAIL';

export const DELETE_BLOG_POST = 'DELETE_BLOG_POST';
export const DELETE_BLOG_POST_FAIL = 'DELETE_BLOG_POST_FAIL';

export const UPDATE_BLOG_POST = 'UPDATE_BLOG_POST';
export const UPDATE_BLOG_POST_FAIL = 'UPDATE_BLOG_POST_FAIL';