export const GET_FACULTIES = 'GET_FACULTIES';
export const GET_FACULTIES_FAIL = 'GET_FACULTIES_FAIL';

export const FETCH_LEVEL_FACULTIES = 'FETCH_LEVEL_FACULTIES';
export const FETCH_LEVEL_FACULTIES_FAIL = 'FETCH_LEVEL_FACULTIES_FAIL';

export const FACULTIES_LOADING = 'FACULTIES_LOADING';

export const CREATE_FACULTY = 'CREATE_FACULTY';
export const CREATE_FACULTY_FAIL = 'CREATE_FACULTY_FAIL';

export const DELETE_FACULTY = 'DELETE_FACULTY';
export const DELETE_FACULTY_FAIL = 'DELETE_FACULTY_FAIL';

export const UPDATE_FACULTY = 'UPDATE_FACULTY';
export const UPDATE_FACULTY_FAIL = 'UPDATE_FACULTY_FAIL';