export const GET_50_NEW_USERS = 'GET_50_NEW_USERS'
export const GET_50_NEW_USERS_FAIL = 'GET_50_NEW_USERS_FAIL'
export const NEW_50_USERS_LOADING = 'NEW_50_USERS_LOADING'

export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'
export const ALL_USERS_LOADING = 'ALL_USERS_LOADING'

export const GET_USERS_WITH_IMAGE = 'GET_USERS_WITH_IMAGE'
export const GET_USERS_WITH_IMAGE_FAIL = 'GET_USERS_WITH_IMAGE_FAIL'
export const USERS_WITH_IMAGE_LOADING = 'USERS_WITH_IMAGE_LOADING'

// users with school 
export const GET_USERS_WITH_SCHOOL = 'GET_USERS_WITH_SCHOOL'
export const GET_USERS_WITH_SCHOOL_FAIL = 'GET_USERS_WITH_SCHOOL_FAIL'
export const USERS_WITH_SCHOOL_LOADING = 'USERS_WITH_SCHOOL_LOADING'

// users with level
export const GET_USERS_WITH_LEVEL = 'GET_USERS_WITH_LEVEL'
export const GET_USERS_WITH_LEVEL_FAIL = 'GET_USERS_WITH_LEVEL_FAIL'
export const USERS_WITH_LEVEL_LOADING = 'USERS_WITH_LEVEL_LOADING'

// users with faculty
export const GET_USERS_WITH_FACULTY = 'GET_USERS_WITH_FACULTY'
export const GET_USERS_WITH_FACULTY_FAIL = 'GET_USERS_WITH_FACULTY_FAIL'
export const USERS_WITH_FACULTY_LOADING = 'USERS_WITH_FACULTY_LOADING'

// users with interests
export const GET_USERS_WITH_INTERESTS = 'GET_USERS_WITH_INTERESTS'
export const GET_USERS_WITH_INTERESTS_FAIL = 'GET_USERS_WITH_INTERESTS_FAIL'
export const USERS_WITH_INTERESTS_LOADING = 'USERS_WITH_INTERESTS_LOADING'

// users with about
export const GET_USERS_WITH_ABOUT = 'GET_USERS_WITH_ABOUT'
export const GET_USERS_WITH_ABOUT_FAIL = 'GET_USERS_WITH_ABOUT_FAIL'
export const USERS_WITH_ABOUT_LOADING = 'USERS_WITH_ABOUT_LOADING'

// top 100 quizzing users
export const GET_TOP_100_QUIZZING_USERS = 'GET_TOP_100_QUIZZING_USERS'
export const GET_TOP_100_QUIZZING_USERS_FAIL = 'GET_TOP_100_QUIZZING_USERS_FAIL'
export const TOP_100_QUIZZING_USERS_LOADING = 'TOP_100_QUIZZING_USERS_LOADING'

// top 100 downloaders
export const GET_TOP_100_DOWNLOADERS = 'GET_TOP_100_DOWNLOADERS'
export const GET_TOP_100_DOWNLOADERS_FAIL = 'GET_TOP_100_DOWNLOADERS_FAIL'
export const TOP_100_DOWNLOADERS_LOADING = 'TOP_100_DOWNLOADERS_LOADING'

// top 20 quizzes
export const GET_TOP_20_QUIZZES = 'GET_TOP_20_QUIZZES'
export const GET_TOP_20_QUIZZES_FAIL = 'GET_TOP_20_QUIZZES_FAIL'
export const TOP_20_QUIZZES_LOADING = 'TOP_20_QUIZZES_LOADING'

// quizzes stats
export const GET_QUIZZES_STATS = 'GET_QUIZZES_STATS'
export const GET_QUIZZES_STATS_FAIL = 'GET_QUIZZES_STATS_FAIL'
export const QUIZZES_STATS_LOADING = 'QUIZZES_STATS_LOADING'

// top 20 notes
export const GET_TOP_20_NOTES = 'GET_TOP_20_NOTES'
export const GET_TOP_20_NOTES_FAIL = 'GET_TOP_20_NOTES_FAIL'
export const TOP_20_NOTES_LOADING = 'TOP_20_NOTES_LOADING'

// notes stats
export const GET_NOTES_STATS = 'GET_NOTES_STATS'
export const GET_NOTES_STATS_FAIL = 'GET_NOTES_STATS_FAIL'
export const NOTES_STATS_LOADING = 'NOTES_STATS_LOADING'

// get quiz category stats
export const GET_QUIZ_CATEGORIES_STATS = 'GET_QUIZ_CATEGORIES_STATS'
export const GET_QUIZ_CATEGORIES_STATS_FAIL = 'GET_QUIZ_CATEGORIES_STATS_FAIL'
export const QUIZ_CATEGORIES_STATS_LOADING = 'QUIZ_CATEGORIES_STATS_LOADING'

// get note category stats
export const GET_NOTE_CATEGORIES_STATS = 'GET_NOTE_CATEGORIES_STATS'
export const GET_NOTE_CATEGORIES_STATS_FAIL = 'GET_NOTE_CATEGORIES_STATS_FAIL'
export const NOTE_CATEGORIES_STATS_LOADING = 'NOTE_CATEGORIES_STATS_LOADING'

// get daily user registration
export const GET_DAILY_USER_REGISTRATION = 'GET_DAILY_USER_REGISTRATION'
export const GET_DAILY_USER_REGISTRATION_FAIL = 'GET_DAILY_USER_REGISTRATION_FAIL'
export const DAILY_USER_REGISTRATION_LOADING = 'DAILY_USER_REGISTRATION_LOADING'

