export const GET_LEVELS = 'GET_LEVELS';
export const GET_LEVELS_FAIL = 'GET_LEVELS_FAIL';

export const FETCH_SCHOOL_LEVELS = 'FETCH_SCHOOL_LEVELS';
export const FETCH_SCHOOL_LEVELS_FAIL = 'FETCH_SCHOOL_LEVELS_FAIL';

export const LEVELS_LOADING = 'LEVELS_LOADING';

export const CREATE_LEVEL = 'CREATE_LEVEL';
export const CREATE_LEVEL_FAIL = 'CREATE_LEVEL_FAIL';

export const DELETE_LEVEL = 'DELETE_LEVEL';
export const DELETE_LEVEL_FAIL = 'DELETE_LEVEL_FAIL';

export const UPDATE_LEVEL = 'UPDATE_LEVEL';
export const UPDATE_LEVEL_FAIL = 'UPDATE_LEVEL_FAIL';