export const GET_CHALLENGES = 'GET_CHALLENGES';
export const CHALLENGES_LOADING = 'CHALLENGES_LOADING';

export const GET_CHALLENGER_CHALLENGES = 'GET_CHALLENGER_CHALLENGES';
export const GET_CHALLENGER_CHALLENGES_FAIL = 'GET_CHALLENGER_CHALLENGES_FAIL';

export const GET_ONE_CHALLENGE = 'GET_ONE_CHALLENGE';
export const GET_ONE_CHALLENGE_FAIL = 'GET_ONE_CHALLENGE_FAIL';

export const CREATE_CHALLENGE = 'CREATE_CHALLENGE';
export const CREATE_CHALLENGE_FAIL = 'CREATE_CHALLENGE_FAIL';

export const UPDATE_CHALLENGE = 'UPDATE_CHALLENGE';
export const UPDATE_CHALLENGE_FAIL = 'UPDATE_CHALLENGE_FAIL';

export const DELETE_CHALLENGE = 'DELETE_CHALLENGE';
export const DELETE_CHALLENGE_FAIL = 'DELETE_CHALLENGE_FAIL';
