export const GET_CHALLENGE_SCORES = 'GET_CHALLENGE_SCORES';
export const CHALLENGE_SCORES_LOADING = 'CHALLENGE_SCORES_LOADING';

export const GET_RANKING_CHALLENGE_SCORES = 'GET_RANKING_CHALLENGE_SCORES';
export const GET_RANKING_CHALLENGE_SCORES_FAIL = 'GET_RANKING_CHALLENGE_SCORES_FAIL';

export const GET_TAKER_CHALLENGE_SCORES = 'GET_TAKER_CHALLENGE_SCORES';
export const GET_TAKER_CHALLENGE_SCORES_FAIL = 'GET_TAKER_CHALLENGE_SCORES_FAIL';

export const GET_CREATOR_CHALLENGE_SCORES = 'GET_CREATOR_CHALLENGE_SCORES';
export const GET_CREATOR_CHALLENGE_SCORES_FAIL = 'GET_CREATOR_CHALLENGE_SCORES_FAIL';

export const GET_ONE_CHALLENGE_SCORE = 'GET_ONE_CHALLENGE_SCORE';
export const GET_ONE_CHALLENGE_SCORE_FAIL = 'GET_ONE_CHALLENGE_SCORE_FAIL';

export const CREATE_CHALLENGE_SCORE = 'CREATE_CHALLENGE_SCORE';
export const CREATE_CHALLENGE_SCORE_FAIL = 'CREATE_CHALLENGE_SCORE_FAIL';

export const UPDATE_CHALLENGE_SCORE = 'UPDATE_CHALLENGE_SCORE';
export const UPDATE_CHALLENGE_SCORE_FAIL = 'UPDATE_CHALLENGE_SCORE_FAIL';

export const DELETE_CHALLENGE_SCORE = 'DELETE_CHALLENGE_SCORE';
export const DELETE_CHALLENGE_SCORE_FAIL = 'DELETE_CHALLENGE_SCORE_FAIL';
