export const SAVE_DOWNLOAD = 'SAVE_DOWNLOAD';
export const SAVE_DOWNLOAD_FAIL = 'SAVE_DOWNLOAD_FAIL';

export const GET_DOWNLOADS = 'GET_DOWNLOADS';
export const GET_DOWNLOADS_FAIL = 'GET_DOWNLOADS_FAIL';

export const GET_USER_DOWNLOADS = 'GET_USER_DOWNLOADS';
export const GET_USER_DOWNLOADS_FAIL = 'GET_USER_DOWNLOADS_FAIL';

export const GET_CREATOR_DOWNLOADS = 'GET_CREATOR_DOWNLOADS';
export const GET_CREATOR_DOWNLOADS_FAIL = 'GET_CREATOR_DOWNLOADS_FAIL';

export const DELETE_DOWNLOAD = 'DELETE_DOWNLOAD';
export const DELETE_DOWNLOAD_FAIL = 'DELETE_DOWNLOAD_FAIL';

export const DOWNLOADS_LOADING = 'DOWNLOADS_LOADING';