export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';

export const GET_ONE_COMMENT = 'GET_ONE_COMMENT';
export const GET_ONE_COMMENT_FAIL = 'GET_ONE_COMMENT_FAIL';

export const GET_QUIZ_COMMENTS = 'GET_QUIZ_COMMENTS';
export const GET_QUIZ_COMMENTS_FAIL = 'GET_QUIZ_COMMENTS_FAIL';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const COMMENTS_LOADING = 'COMMENTS_LOADING';