export const GET_CHAPTERS = 'GET_CHAPTERS';
export const GET_CHAPTERS_FAIL = 'GET_CHAPTERS_FAIL';

export const GET_CHAPTERS_BY_COURSE = 'GET_CHAPTERS_BY_COURSE';
export const GET_CHAPTERS_BY_COURSE_FAIL = 'GET_CHAPTERS_BY_COURSE_FAIL';

export const CREATE_CHAPTER = 'CREATE_CHAPTER';
export const CREATE_CHAPTER_FAIL = 'CREATE_CHAPTER_FAIL';

export const DELETE_CHAPTER = 'DELETE_CHAPTER';
export const DELETE_CHAPTER_FAIL = 'DELETE_CHAPTER_FAIL';

export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';
export const UPDATE_CHAPTER_FAIL = 'UPDATE_CHAPTER_FAIL';

export const CHAPTERS_LOADING = 'CHAPTERS_LOADING';
export const CHAPTERS_BY_COURSE_LOADING = 'CHAPTERS_BY_COURSE_LOADING';