export const SET_QUIZES = 'SET_QUIZES'
export const QUIZES_LOADING = 'QUIZES_LOADING'

export const GET_ONE_QUIZ = 'GET_ONE_QUIZ'
export const GET_ONE_QUIZ_FAIL = 'GET_ONE_QUIZ_FAIL'

export const GET_CATEGORY_QUIZES = 'GET_CATEGORY_QUIZES'
export const GET_CATEGORY_QUIZES_FAIL = 'GET_CATEGORY_QUIZES_FAIL'

export const GET_NOTES_QUIZES = 'GET_NOTES_QUIZES'
export const GET_NOTES_QUIZES_FAIL = 'GET_NOTES_QUIZES_FAIL'

export const DELETE_VIDEO = 'DELETE_VIDEO'
export const DELETE_VIDEO_FAIL = 'DELETE_VIDEO_FAIL'

export const ADD_VIDEO_LINK = 'ADD_VIDEO_LINK'
export const ADD_VIDEO_LINK_FAIL = 'ADD_VIDEO_LINK_FAIL'

export const CREATE_QUIZ = 'CREATE_QUIZ'
export const CREATE_QUIZ_FAIL = 'CREATE_QUIZ_FAIL'

export const NOTIFY_USERS = 'NOTIFY_USERS'
export const NOTIFY_USERS_FAIL = 'NOTIFY_USERS_FAIL'

export const UPDATE_QUIZ = 'UPDATE_QUIZ'
export const UPDATE_QUIZ_FAIL = 'UPDATE_QUIZ_FAIL'

export const DELETE_QUIZ = 'DELETE_QUIZ'
export const DELETE_QUIZ_FAIL = 'DELETE_QUIZ_FAIL'

export const SET_ALL_QUIZES = 'SET_ALL_QUIZES'
export const ALL_QUIZES_LOADING = 'ALL_QUIZES_LOADING'
