export const SET_POSTS = 'SET_POSTS';
export const GET_POSTS = 'GET_POSTS';

export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';

export const SUBSCRIBETONEWSLETTER = 'SUBSCRIBETONEWSLETTER';
export const SUBSCRIBE_FAIL = 'SUBSCRIBE_FAIL';

export const SET_SUBSCRIBERS = 'SET_SUBSCRIBERS';
export const SUBSCRIBERS_LOADING = 'SUBSCRIBERS_LOADING';
export const GET_SUBSCRIBER = 'GET_SUBSCRIBER';

export const DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER';
export const DELETE_SUBSCRIBER_FAIL = 'DELETE_SUBSCRIBER_FAIL';