export const GET_IMAGE_UPLOADS = 'GET_IMAGE_UPLOADS';
export const GET_IMAGE_UPLOADS_FAIL = 'GET_IMAGE_UPLOADS_FAIL';

export const GET_ONE_IMAGE_UPLOAD = 'GET_IMAGE_UPLOAD';
export const GET_ONE_IMAGE_UPLOAD_FAIL = 'GET_ONE_IMAGE_UPLOAD_FAIL';

export const GET_IMAGE_UPLOADS_BY_OWNER = 'GET_IMAGE_UPLOADS_BY_OWNER';
export const GET_IMAGE_UPLOADS_BY_OWNER_FAIL = 'GET_IMAGE_UPLOADS_BY_OWNER_FAIL';

export const IMAGE_UPLOADS_LOADING = 'IMAGE_UPLOADS_LOADING';

export const CREATE_IMAGE_UPLOAD = 'CREATE_IMAGE_UPLOAD';
export const CREATE_IMAGE_UPLOAD_FAIL = 'CREATE_IMAGE_UPLOAD_FAIL';

export const DELETE_IMAGE_UPLOAD = 'DELETE_IMAGE_UPLOAD';
export const DELETE_IMAGE_UPLOAD_FAIL = 'DELETE_IMAGE_UPLOAD_FAIL';

export const UPDATE_IMAGE_UPLOAD = 'UPDATE_IMAGE_UPLOAD';
export const UPDATE_IMAGE_UPLOAD_FAIL = 'UPDATE_IMAGE_UPLOAD_FAIL';