export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_FAIL = 'SET_CATEGORIES_FAIL';

export const GET_ONE_CATEGORY_FAIL = 'GET_ONE_CATEGORY_FAIL';
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

