export const GET_COURSES = 'GET_COURSES';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const GET_ONE_COURSE = 'GET_ONE_COURSE';
export const GET_ONE_COURSE_FAIL = 'GET_ONE_COURSE_FAIL';

export const COURSES_LOADING = 'COURSES_LOADING';
export const ONE_COURSE_LOADING = 'ONE_COURSE_LOADING';
export const COURSES_BYCAT_LOADING = 'COURSES_BYCAT_LOADING';

export const GET_COURSES_BY_CATEGORY = 'GET_COURSES_BY_CATEGORY';
export const GET_COURSES_BY_CATEGORY_FAIL = 'GET_COURSES_BY_CATEGORY_FAIL';

export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSE_FAIL = 'CREATE_COURSE_FAIL';

export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL';

export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL';