export const GET_POST_CATEGORIES = 'GET_POST_CATEGORIES';
export const GET_POST_CATEGORIES_FAIL = 'GET_POST_CATEGORIES_FAIL';

export const POST_CATEGORIES_LOADING = 'POST_CATEGORIES_LOADING';

export const CREATE_POST_CATEGORY = 'CREATE_POST_CATEGORY';
export const CREATE_POST_CATEGORY_FAIL = 'CREATE_POST_CATEGORY_FAIL';

export const DELETE_POST_CATEGORY = 'DELETE_POST_CATEGORY';
export const DELETE_POST_CATEGORY_FAIL = 'DELETE_POST_CATEGORY_FAIL';

export const UPDATE_POST_CATEGORY = 'UPDATE_POST_CATEGORY';
export const UPDATE_POST_CATEGORY_FAIL = 'UPDATE_POST_CATEGORY_FAIL';