export const GET_ADVERTS = 'GET_ADVERTS'
export const GET_ADVERTS_FAIL = 'GET_ADVERTS_FAIL'

export const GET_ONE_ADVERT_FAIL = 'GET_ONE_ADVERT_FAIL'
export const GET_ONE_ADVERT = 'GET_ONE_ADVERT'

export const ADVERTS_LOADING = 'ADVERTS_LOADING'

export const CREATE_ADVERT = 'CREATE_ADVERT'
export const CREATE_ADVERT_FAIL = 'CREATE_ADVERT_FAIL'

export const UPDATE_ADVERT = 'UPDATE_ADVERT'
export const UPDATE_ADVERT_FAIL = 'UPDATE_ADVERT_FAIL'

export const DELETE_ADVERT = 'DELETE_ADVERT'
export const DELETE_ADVERT_FAIL = 'DELETE_ADVERT_FAIL'