export const SET_BROADCASTS = 'SET_BROADCASTS';
export const SET_BROADCASTS_FAIL = 'SET_BROADCASTS_FAIL';

export const GET_ONE_BROADCAST_FAIL = 'GET_ONE_BROADCAST_FAIL';
export const GET_ONE_BROADCAST = 'GET_ONE_BROADCAST';

export const BROADCASTS_LOADING = 'BROADCASTS_LOADING';

export const CREATE_BROADCAST = 'CREATE_BROADCAST';
export const CREATE_BROADCAST_FAIL = 'CREATE_BROADCAST_FAIL';

export const DELETE_BROADCAST = 'DELETE_BROADCAST';
export const DELETE_BROADCAST_FAIL = 'DELETE_BROADCAST_FAIL';

